### ISSUE TITLE
Mod refuses to load with any version of StationAPI

### ISSUE THREAD

**Issue by LunatiK-ExpiX** [kozibrodka/BetterThanWolves#5]
Ditto, I tried running with Alpha 1.1 and Alpha 2.0-2.3. 
This error is the result.
`A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'station-api-base'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.24-babric.1.jar:?]
	at org.prismlauncher.legacy.LegacyLauncher.launch(LegacyLauncher.java:123) [NewLaunchLegacy.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'station-api-base'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.14.24-babric.1.jar:?]
	... 5 more
Caused by: java.lang.NoClassDefFoundError: net/glasslauncher/hmifabric/tabs/Tab
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.modificationstation.stationapi.api.StationAPI.lambda$setupEntrypoint$1(StationAPI.java:86) ~[station-api-base-2.0-alpha.1.1-1.0.0-c5a766dcbe3009cb.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at net.modificationstation.stationapi.api.StationAPI.setupEntrypoint(StationAPI.java:85) ~[station-api-base-2.0-alpha.1.1-1.0.0-c5a766dcbe3009cb.jar:?]
	at net.modificationstation.stationapi.api.StationAPI.setupMods(StationAPI.java:71) ~[station-api-base-2.0-alpha.1.1-1.0.0-c5a766dcbe3009cb.jar:?]
	at net.modificationstation.stationapi.api.StationAPI.onPreLaunch(StationAPI.java:62) ~[station-api-base-2.0-alpha.1.1-1.0.0-c5a766dcbe3009cb.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.14.24-babric.1.jar:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.glasslauncher.hmifabric.tabs.Tab
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.modificationstation.stationapi.api.StationAPI.lambda$setupEntrypoint$1(StationAPI.java:86) ~[station-api-base-2.0-alpha.1.1-1.0.0-c5a766dcbe3009cb.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at net.modificationstation.stationapi.api.StationAPI.setupEntrypoint(StationAPI.java:85) ~[station-api-base-2.0-alpha.1.1-1.0.0-c5a766dcbe3009cb.jar:?]
	at net.modificationstation.stationapi.api.StationAPI.setupMods(StationAPI.java:71) ~[station-api-base-2.0-alpha.1.1-1.0.0-c5a766dcbe3009cb.jar:?]
	at net.modificationstation.stationapi.api.StationAPI.onPreLaunch(StationAPI.java:62) ~[station-api-base-2.0-alpha.1.1-1.0.0-c5a766dcbe3009cb.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.14.24-babric.1.jar:?]
	... 5 more
`

**Comment by Atilist** [comment]
Sorry for responding extremely late. I am not exactly sure what causes this issue and I would recommend you to try the newest update (1.1.0 as of writing this) and make sure that all dependencies are installed (GlassConfigAPI is required, Always More Items is optional). The compatible Station API version is Alpha 3 now. If you have any issues again, please either create a new issue or comment in this one. I will check issues more frequently so I can respond sooner
